#!/usr/bin/env sh

# get all data info
get_log() {
    git log --since=1.years --numstat --pretty="%ae %H"
}

# replace username@email.com to username
sed_data() {
    get_log | sed 's/@.*//g'
}

# filter useful data
awk_data() {
    sed_data | awk '{ 
        if (NF == 1){ 
            name = $1
        }; 
        if(NF == 3) {
            plus[name] += $1; 
            minus[name] += $2
        }
    } END { 
        for (name in plus) {
            printf name": \t\033[1;31m+"plus[name]" \t\033[1;32m-"minus[name]"\033[0m \tdiff: "plus[name]-minus[name]"\n"
        }
    }'
}

# print data with sorted
main() {
    printf "\nPass 1 Year code line(s)\n\n"
    awk_data | sort -k2 -gr
    printf "\n"
}

main
